language: csharp
mono: latest
# .NET Core
dotnet: 3.1 
script:
 # - ./build.sh
  - if [[ $DEPLOY_DOCS ]]; then ./build.sh -t Docs; fi  
deploy:
- provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: docs/_site
  on:
    branch: gh-pages
